language: node_js
node_js:
  - '7'

cache:
  yarn: true
  directories:
    - "$HOME/.npm"
    - "$HOME/.yarn-cache"

script:
 - npm run lint --max-warnings=0

deploy:
  - provider: npm
    email: "info@nfq.lt"
    on:
      tags: true
